---
id: ManageSieve
name: ManageSieve
full: ManageSieve client library
description: A library that implements the ManageSieve protocol (RFC 5804).
list: dev
type: library
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 1.0.4
  api: 1.0.0
state:
  release: stable
  api: stable
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^5.4
    pear:
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Socket_Client: ^2
      pear.horde.org/Horde_Util: ^2
  optional:
    pear:
      pear.php.net/Auth_SASL: ^1
